### ISSUE TITLE
reconnect bug seen on BV5500Pro

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#22]
0.5.7

```
Non-fatal Exception: java.lang.AssertionError: Assertion failed
       at com.geeksville.android.Logging$DefaultImpls.logAssert(Logging.java:51)
       at com.geeksville.mesh.service.SafeBluetooth.logAssert(SafeBluetooth.java:50)
       at com.geeksville.mesh.service.SafeBluetooth.asyncConnect(SafeBluetooth.java:421)
       at com.geeksville.mesh.service.RadioInterfaceService.startConnect(RadioInterfaceService.java:525)
       at com.geeksville.mesh.service.RadioInterfaceService.retryDueToException(RadioInterfaceService.java:408)
       at com.geeksville.mesh.service.RadioInterfaceService$retryDueToException$1.invokeSuspend(RadioInterfaceService.java:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

[com.geeksville.mesh_issue_2a12c7f9d75db78e3f3f9648aff2177a_error_session_5EA52BD503B000014811AF414342D51E_DNE_0_v2.log](https://github.com/meshtastic/Meshtastic-Android/files/4536321/com.geeksville.mesh_issue_2a12c7f9d75db78e3f3f9648aff2177a_error_session_5EA52BD503B000014811AF414342D51E_DNE_0_v2.log)

**Comment by geeksville** [comment]
fixed I bet
