### ISSUE TITLE
currentWork was !null

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#67]
@feh123, this is the bug you reported - I'm finally working on it ;-)

Root cause log:
Non-fatal Exception: java.lang.AssertionError: currentWork was not null: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@76021b6
       at com.geeksville.mesh.service.SafeBluetooth.asyncConnect(SafeBluetooth.java:497)
       at com.geeksville.mesh.service.BluetoothInterface.startConnect(BluetoothInterface.java:435)
       at com.geeksville.mesh.service.BluetoothInterface.retryDueToException(BluetoothInterface.java:333)
       at com.geeksville.mesh.service.BluetoothInterface$retryDueToException$1.invokeSuspend(BluetoothInterface.java)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

[com.geeksville.mesh_issue__error_session_5EEF0C36032E00014F61BF14B4903F25_DNE_0_v2.log](https://github.com/meshtastic/Meshtastic-Android/files/4834245/com.geeksville.mesh_issue__error_session_5EEF0C36032E00014F61BF14B4903F25_DNE_0_v2.log)

From button press:
[com.geeksville.mesh_issue__error_session_5EF08DF2011000010B0B574425F520AD_DNE_2_v2.log](https://github.com/meshtastic/Meshtastic-Android/files/4834251/com.geeksville.mesh_issue__error_session_5EF08DF2011000010B0B574425F520AD_DNE_2_v2.log)

**Comment by geeksville** [comment]
relevant portion of log (just a note to myself)

```

486 | Sun Jun 21 2020 01:03:04 GMT-0700 (Pacific Daylight Time) | screen_view
487 | Sun Jun 21 2020 01:03:04 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.ui.BTScanModel: onScanResult DeviceListEntry(name=...5f4, addr=...:F6)
488 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.ui.BTScanModel: Changing device to ...:F6
489 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Passing through device change to radio service: x24:62:AB:F8:75:F6
490 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.analytics.GoogleAnalytics: Analytics: track mesh_bond
491 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: stopping interface com.geeksville.mesh.service.BluetoothInterface@296a17f4
492 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Closing radio interface service
493 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
494 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Setting bonded device to x24:62:AB:F8:75:F6
495 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Starting radio x24:62:AB:F8:75:F6
496 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Creating radio interface service.  device=...:F6
497 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: connect
498 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: connect
499 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService$Companion: Trying to start service
500 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Requesting foreground service=true
501 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | mesh_bond
502 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 2, status 0
503 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work connect is completed, resuming status=0, res=kotlin.Unit
504 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Connected to radio!
505 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reqMtu
506 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reqMtu
507 | Sun Jun 21 2020 01:03:07 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Starting failsafe timer 5000
508 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Failsafe BLE timer expired! (exception none
509 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work reqMtu is completed, resuming status=4404, res=kotlin.Unit
510 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Scheduling reconnect because Giving up on setting MTUs, forcing disconnect com.geeksville.mesh.service.SafeBluetooth$BLEStatusException: Bluetooth status=4404 while doing reqMtu
511 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Forcing disconnect and hopefully device will comeback (disabling forced refresh)
512 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
513 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 0, status 0
514 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: No gatt: ignoring connection state 0, status 0
515 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.ui.BTScanModel: Changing device to ...:5A
516 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Passing through device change to radio service: x24:62:AB:F8:49:5A
517 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.analytics.GoogleAnalytics: Analytics: track mesh_bond
518 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: stopping interface com.geeksville.mesh.service.BluetoothInterface@a2454de
519 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Closing radio interface service
520 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Setting bonded device to x24:62:AB:F8:49:5A
521 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Starting radio x24:62:AB:F8:49:5A
522 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Creating radio interface service.  device=...:5A
523 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: connect
524 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: connect
525 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService$Companion: Trying to start service
526 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Requesting foreground service=true
527 | Sun Jun 21 2020 01:03:12 GMT-0700 (Pacific Daylight Time) | mesh_bond
528 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 2, status 0
529 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work connect is completed, resuming status=0, res=kotlin.Unit
530 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Connected to radio!
531 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reqMtu
532 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reqMtu
533 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Starting failsafe timer 5000
534 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 0, status 62
535 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Lost connection - aborting current work: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@34dd0551
536 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: calling lostConnect handler
537 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: queuing a reconnection callback
538 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
539 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reconnect
540 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reconnect
541 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Attempting reconnect
542 | Sun Jun 21 2020 01:03:13 GMT-0700 (Pacific Daylight Time) | com.geeksville.util.Exceptions: MeshService-coroutine coroutine-exception (exception currentWork was not null: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@76021b6
```

**Comment by geeksville** [comment]
preceeding log analysis (marked with ***) means that in the onConnectionStateChange callback, gatt was !null.  But it should have been null by then because a different thread had already called closeGatt().  Therefore the problem is that gatt should be @Volatile.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/alpha-tester-thread-please-try-device-0-7-9-and-android-0-7-81/298/116
