### ISSUE TITLE
the first time we attempt to connect after pairing, exception:

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#7]
```
2020-03-15 16:22:08.488 7510-7622/com.geeksville.mesh D/CrashJobIntentService: onHandleWork
2020-03-15 16:22:08.489 7510-7622/com.geeksville.mesh W/CrashJobIntentService: Root directory doesn't exist
2020-03-15 16:22:08.629 7510-7529/com.geeksville.mesh D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=10 device=24:6F:28:96:C9:2A
2020-03-15 16:22:08.630 7510-7529/com.geeksville.mesh I/com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 2, status 0
2020-03-15 16:22:08.630 7510-7529/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: work connect is completed, resuming status=0, res=kotlin.Unit
2020-03-15 16:22:08.631 7510-7529/com.geeksville.mesh I/com.geeksville.mesh.service.RadioInterfaceService: Connected to radio!
2020-03-15 16:22:08.631 7510-7529/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: discover
2020-03-15 16:22:08.631 7510-7529/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: discover
2020-03-15 16:22:08.631 7510-7529/com.geeksville.mesh D/BluetoothGatt: discoverServices() - device: 24:6F:28:96:C9:2A
2020-03-15 16:22:09.530 7510-7733/com.geeksville.mesh D/BluetoothGatt: onConnectionUpdated() - Device=24:6F:28:96:C9:2A interval=6 latency=0 timeout=500 status=0
2020-03-15 16:22:10.128 7510-7733/com.geeksville.mesh D/BluetoothGatt: onSearchComplete() = Device=24:6F:28:96:C9:2A Status=0
2020-03-15 16:22:10.128 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: work discover is completed, resuming status=0, res=kotlin.Unit
2020-03-15 16:22:10.128 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.RadioInterfaceService: Discovered services!
2020-03-15 16:22:10.129 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reqMtu
2020-03-15 16:22:10.129 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reqMtu
2020-03-15 16:22:10.129 7510-7733/com.geeksville.mesh D/BluetoothGatt: configureMTU() - device: 24:6F:28:96:C9:2A mtu: 512
2020-03-15 16:22:10.146 7510-7733/com.geeksville.mesh D/BluetoothGatt: onConfigureMTU() - Device=24:6F:28:96:C9:2A mtu=512 status=0
2020-03-15 16:22:10.146 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: work reqMtu is completed, resuming status=0, res=kotlin.Unit
2020-03-15 16:22:10.147 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.RadioInterfaceService: requested MTU result=Success(kotlin.Unit)
2020-03-15 16:22:10.147 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: starting setNotify(ed9da18c-a800-4f66-a670-aa7547e34453, true)
2020-03-15 16:22:10.147 7510-7733/com.geeksville.mesh D/BluetoothGatt: setCharacteristicNotification() - uuid: ed9da18c-a800-4f66-a670-aa7547e34453 enable: true
2020-03-15 16:22:10.148 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: writeD
2020-03-15 16:22:10.149 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: writeD
2020-03-15 16:22:10.149 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.RadioInterfaceService: Broadcasting connection=true
2020-03-15 16:22:10.151 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: readC 8ba2bcc2-ee02-4a55-a531-c525c5e454d5
2020-03-15 16:22:10.153 7510-7510/com.geeksville.mesh D/com.geeksville.mesh.service.MeshService: Received broadcast com.geeksville.mesh.CONNECT_CHANGED
2020-03-15 16:22:10.154 7510-7510/com.geeksville.mesh D/com.geeksville.mesh.service.MeshService: onConnectionChanged connected=true
2020-03-15 16:22:10.155 7510-7510/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: readC ea9f3f82-8dc4-4733-9452-1f6da28892a2
2020-03-15 16:22:10.168 7510-7530/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: readC 8ba2bcc2-ee02-4a55-a531-c525c5e454d5
2020-03-15 16:22:10.169 7510-7530/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: work writeD is completed, resuming status=0, res=android.bluetooth.BluetoothGattDescriptor@9a13b8a
2020-03-15 16:22:10.169 7510-7530/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: Notify enable=true completed
2020-03-15 16:22:10.248 7510-7530/com.geeksville.mesh D/BluetoothGatt: onConnectionUpdated() - Device=24:6F:28:96:C9:2A interval=36 latency=0 timeout=500 status=0
2020-03-15 16:22:30.291 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: readC ea9f3f82-8dc4-4733-9452-1f6da28892a2
2020-03-15 16:22:30.292 7510-7733/com.geeksville.mesh D/com.geeksville.mesh.service.SafeBluetooth: work readC 8ba2bcc2-ee02-4a55-a531-c525c5e454d5 is completed, resuming status=137, res=android.bluetooth.BluetoothGattCharacteristic@8695fb
2020-03-15 16:22:30.293 7510-7733/com.geeksville.mesh E/com.geeksville.util.Exceptions: exceptionReporter Uncaught Exception
    java.io.IOException: Bluetooth status=137 while doing readC 8ba2bcc2-ee02-4a55-a531-c525c5e454d5
        at com.geeksville.mesh.service.SafeBluetooth$completeWork$1.invoke(SafeBluetooth.kt:326)
        at com.geeksville.mesh.service.SafeBluetooth$completeWork$1.invoke(Unknown Source:0)
        at com.geeksville.util.ExceptionsKt.exceptionReporter(Exceptions.kt:31)
        at com.geeksville.mesh.service.SafeBluetooth.completeWork(SafeBluetooth.kt:311)
        at com.geeksville.mesh.service.SafeBluetooth.access$completeWork$2(Unknown Source:0)
        at com.geeksville.mesh.service.SafeBluetooth$gattCallback$1.onCharacteristicRead(SafeBluetooth.kt:206)
        at android.bluetooth.BluetoothGatt$1$6.run(BluetoothGatt.java:394)
        at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:780)
        at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:41)
        at android.bluetooth.BluetoothGatt$1.onCharacteristicRead(BluetoothGatt.java:388)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:246)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-03-15 16:22:40.156 7510-7510/com.geeksville.mesh E/toRemoteExceptions: Uncaught exception, returning to remote client
    java.lang.Exception: SyncContinuation timeout
        at com.geeksville.concurrent.SyncContinuation.await(SyncContinuation.kt:49)
        at com.geeksville.mesh.service.SafeBluetooth.makeSync(SafeBluetooth.kt:349)
        at com.geeksville.mesh.service.SafeBluetooth.readCharacteristic(SafeBluetooth.kt:410)
        at com.geeksville.mesh.service.RadioInterfaceService$doRead$1.invoke(RadioInterfaceService.kt:418)
        at com.geeksville.mesh.service.RadioInterfaceService$doRead$1.invoke(Unknown Source:0)
        at com.geeksville.util.ExceptionsKt.toRemoteExceptions(Exceptions.kt:41)
        at com.geeksville.mesh.service.RadioInterfaceService.doRead(RadioInterfaceService.kt:411)
        at com.geeksville.mesh.service.RadioInterfaceService.access$doRead$3(Unknown Source:0)
        at com.geeksville.mesh.service.RadioInterfaceService$binder$1.readMyNode(RadioInterfaceService.kt:437)
        at com.geeksville.mesh.service.MeshService.reinitFromRadio(MeshService.kt:610)
        at com.geeksville.mesh.service.MeshService.onConnectionChanged(MeshService.kt:693)
        at com.geeksville.mesh.service.MeshService.access$onConnectionChanged$5(Unknown Source:0)
        at com.geeksville.mesh.service.MeshService$radioInterfaceReceiver$1$onReceive$1.invoke(MeshService.kt:744)
        at com.geeksville.mesh.service.MeshService$radioInterfaceReceiver$1$onReceive$1.invoke(Unknown Source:0)
        at com.geeksville.util.ExceptionsKt.exceptionReporter(Exceptions.kt:31)
        at com.geeksville.mesh.service.MeshService$radioInterfaceReceiver$1.onReceive(MeshService.kt:738)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-03-15 16:22:40.156 7510-7510/com.geeksville.mesh W/com.geeksville.mesh.service.MeshService: Abandoning reconnect attempt, due to errors during init: SyncContinuation timeout

```

**Comment by geeksville** [comment]
fixed
