### ISSUE TITLE
currentWork was null 0.7.84

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#77]
Non-fatal Exception: java.lang.Exception: currentWork was null
       at com.geeksville.mesh.service.SafeBluetooth$completeWork$1.invoke(SafeBluetooth.java:372)
       at com.geeksville.mesh.service.SafeBluetooth$completeWork$1.invoke(SafeBluetooth.java:32)
       at com.geeksville.util.ExceptionsKt.exceptionReporter(ExceptionsKt.java:34)
       at com.geeksville.mesh.service.SafeBluetooth.completeWork(SafeBluetooth.java:364)
       at com.geeksville.mesh.service.SafeBluetooth.access$completeWork(SafeBluetooth.java:32)
       at com.geeksville.mesh.service.SafeBluetooth$gattCallback$1$onConnectionStateChange$1.invoke(SafeBluetooth.java:144)
       at com.geeksville.mesh.service.SafeBluetooth$gattCallback$1$onConnectionStateChange$1.invoke(SafeBluetooth.java:126)
       at com.geeksville.util.ExceptionsKt.exceptionReporter(ExceptionsKt.java:34)
       at com.geeksville.mesh.service.SafeBluetooth$gattCallback$1.onConnectionStateChange(SafeBluetooth.java:132)
       at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:272)
       at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:780)
       at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:41)
       at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:267)
       at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:192)
       at android.os.Binder.execTransactInternal(Binder.java:1021)
       at android.os.Binder.execTransact(Binder.java:994)

**Comment by geeksville** [comment]
alas logs are useless because "HMD Global" filtered them

**Comment by geeksville** [comment]
reopen once better logs arrive

**Comment by geeksville** [comment]
better logs here from @feh123
June 27th 0.7.81
Seems to occur during a reconnect attempt

```
Non-fatal Exception: java.lang.AssertionError: currentWork was not null: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@2212e2ed
       at com.geeksville.mesh.service.SafeBluetooth.asyncConnect(SafeBluetooth.java:498)
       at com.geeksville.mesh.service.BluetoothInterface.startConnect(BluetoothInterface.java:440)
       at com.geeksville.mesh.service.BluetoothInterface.retryDueToException(BluetoothInterface.java:334)
       at com.geeksville.mesh.service.BluetoothInterface$retryDueToException$1.invokeSuspend(BluetoothInterface.java)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

[com.geeksville.mesh_issue__error_session_5EF728CC01070001197406DB5E1595C6_DNE_0_v2.log](https://github.com/meshtastic/Meshtastic-Android/files/4861149/com.geeksville.mesh_issue__error_session_5EF728CC01070001197406DB5E1595C6_DNE_0_v2.log)

**Comment by geeksville** [comment]
relevant portion of logs

```
322 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work connect is completed, resuming status=0, res=kotlin.Unit
323 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Connected to radio!
324 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | mesh_bond
325 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reqMtu
326 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reqMtu
327 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Starting failsafe timer 5000
328 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.ui.BTScanModel: Changing device to ...:F6
329 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Passing through device change to radio service: x24:62:AB:F8:75:F6
330 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.analytics.GoogleAnalytics: Analytics: track mesh_bond
331 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: stopping interface com.geeksville.mesh.service.BluetoothInterface@333fa427
332 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Closing radio interface service
333 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
334 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 0, status 0
335 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: No gatt: ignoring connection state 0, status 0
336 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Setting bonded device to x24:62:AB:F8:75:F6
337 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Starting radio x24:62:AB:F8:75:F6
338 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Creating radio interface service.  device=...:F6
339 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: connect
340 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: connect
341 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService$Companion: Trying to start service
342 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 2, status 0
343 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work connect is completed, resuming status=0, res=kotlin.Unit
344 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Connected to radio!
345 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Requesting foreground service=true
346 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reqMtu
347 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reqMtu
348 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Starting failsafe timer 5000
349 | Sat Jun 27 2020 04:13:02 GMT-0700 (Pacific Daylight Time) | mesh_bond
350 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work reqMtu is completed, resuming status=10, res=kotlin.Unit
351 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Scheduling reconnect because Giving up on setting MTUs, forcing disconnect com.geeksville.mesh.service.SafeBluetooth$BLEStatusException: Bluetooth status=10 while doing reqMtu
352 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Forcing disconnect and hopefully device will comeback (disabling forced refresh)
353 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
354 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 0, status 0
355 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: No gatt: ignoring connection state 0, status 0
356 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.ui.BTScanModel: Changing device to ...:5A
357 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Passing through device change to radio service: x24:62:AB:F8:49:5A
358 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.analytics.GoogleAnalytics: Analytics: track mesh_bond
359 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: stopping interface com.geeksville.mesh.service.BluetoothInterface@32530779
360 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Closing radio interface service
361 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Setting bonded device to x24:62:AB:F8:49:5A
362 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Starting radio x24:62:AB:F8:49:5A
363 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Creating radio interface service.  device=...:5A
364 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: connect
365 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: connect
366 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService$Companion: Trying to start service
367 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Requesting foreground service=true
368 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | mesh_bond
369 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.ui.BTScanModel: Changing device to ...:F6
370 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Passing through device change to radio service: x24:62:AB:F8:75:F6
371 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.analytics.GoogleAnalytics: Analytics: track mesh_bond
372 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: stopping interface com.geeksville.mesh.service.BluetoothInterface@1367803b
373 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Closing radio interface service
374 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
375 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Setting bonded device to x24:62:AB:F8:75:F6
376 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Starting radio x24:62:AB:F8:75:F6
377 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Creating radio interface service.  device=...:F6
378 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: connect
379 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: connect
380 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService$Companion: Trying to start service
381 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 2, status 0
382 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work connect is completed, resuming status=0, res=kotlin.Unit
383 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Connected to radio!
384 | Sat Jun 27 2020 04:13:03 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Requesting foreground service=true
385 | Sat Jun 27 2020 04:13:04 GMT-0700 (Pacific Daylight Time) | mesh_bond
386 | Sat Jun 27 2020 04:13:04 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reqMtu
387 | Sat Jun 27 2020 04:13:04 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reqMtu
388 | Sat Jun 27 2020 04:13:04 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Starting failsafe timer 5000
389 | Sat Jun 27 2020 04:13:04 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Attempting reconnect
390 | Sat Jun 27 2020 04:13:04 GMT-0700 (Pacific Daylight Time) | com.geeksville.util.Exceptions: MeshService-coroutine coroutine-exception (exception currentWork was not null: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@2212e2ed
```

**Comment by geeksville** [comment]
0.7.85

```
Non-fatal Exception: java.lang.AssertionError: currentWork was not null: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@f988773
       at com.geeksville.mesh.service.SafeBluetooth.asyncConnect(SafeBluetooth.java:483)
       at com.geeksville.mesh.service.BluetoothInterface.startConnect(BluetoothInterface.java:451)
       at com.geeksville.mesh.service.BluetoothInterface.retryDueToException(BluetoothInterface.java:338)
       at com.geeksville.mesh.service.BluetoothInterface$retryDueToException$1.invokeSuspend(BluetoothInterface.java:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```
[com.geeksville.mesh_issue__error_session_5EFDD0C50105000142AD0498DA5D0F63_DNE_0_v2.log](https://github.com/meshtastic/Meshtastic-Android/files/4865186/com.geeksville.mesh_issue__error_session_5EFDD0C50105000142AD0498DA5D0F63_DNE_0_v2.log)

**Comment by geeksville** [comment]
root cause in log:
the problem is that we are running dropAndReconnect (because of an error diduing writec) at the same time as handleSendToRadio called scheduleReconnect because of the exception

fix is: now that BluetoothInterface is smart enough to do its own reconnections, do not auto reconnect in SafeBluetooth.  Instead just throw a BLEException and assume the client will reconnect if it wants.


'''

300 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: onConnectionChanged=CONNECTED
301 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Starting config nonce=3
302 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: new bluetooth connection state 0, status 22
303 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Lost connection - aborting current work: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@7b193fb *** handle loss of connection callback
304 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: queuing 3 bytes to f75c76d2-129e-4dad-a1dd-7866124401e7
305 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Failing 0 works, because Lost connection
306 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: calling lostConnect handler *** this was in dropAndReconnect
307 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.RadioInterfaceService: Broadcasting connection=false
308 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: writeC f75c76d2-129e-4dad-a1dd-7866124401e7
309 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: writeC f75c76d2-129e-4dad-a1dd-7866124401e7
310 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Failed to start work, returned error status
311 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: work writeC f75c76d2-129e-4dad-a1dd-7866124401e7 is completed, resuming status=4405, res=kotlin.Unit
312 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Scheduling reconnect because error during asyncWriteCharacteristic - disconnecting, Bluetooth status=4405 while doing writeC f75c76d2-129e-4dad-a1dd-7866124401e7 *** this scheduled the recoonect
313 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: queuing a reconnection callback *** dropAndReconnect
314 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
315 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Forcing disconnect and hopefully device will comeback (disabling forced refresh)
316 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Closing our GATT connection
317 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Received broadcast com.geeksville.mesh.CONNECT_CHANGED
318 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: onConnectionChanged=DEVICE_SLEEP
319 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.analytics.GoogleAnalytics: Analytics: track connected_seconds
320 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.MeshService: Waiting for sleeping device, timeout=3630 secs
321 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.MainActivity: Received from mesh service Intent { act=com.geeksville.mesh.MESH_CONNECTED flg=0x10 (has extras) }
322 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.MainActivity: connchange DEVICE_SLEEP
323 | Thu Jul 02 2020 05:19:35 GMT-0700 (Pacific Daylight Time) | connected_seconds
324 | Thu Jul 02 2020 05:19:36 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Android onConnectionStateChange did not run, manually closing
325 | Thu Jul 02 2020 05:19:36 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Failing 0 works, because Connection closing
326 | Thu Jul 02 2020 05:19:36 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth: Enqueuing work: reconnect *** where did this come from?
327 | Thu Jul 02 2020 05:19:36 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation: Starting work: reconnect
328 | Thu Jul 02 2020 05:19:37 GMT-0700 (Pacific Daylight Time) | com.geeksville.mesh.service.BluetoothInterface: Attempting reconnect
329 | Thu Jul 02 2020 05:19:37 GMT-0700 (Pacific Daylight Time) | com.geeksville.util.Exceptions: MeshService-coroutine coroutine-exception (exception currentWork was not null: com.geeksville.mesh.service.SafeBluetooth$BluetoothContinuation@f988773)'''
